### ISSUE TITLE
checkbox/fantasy: Bad variable in compiled CSS

### ISSUE THREAD

**Issue by artptr** [alfa-laboratory/arui-feather#108]
arui-feather@6.6.1

```
WARNING in ./~/css-loader?sourceMap!./~/postcss-loader!./~/arui-feather/checkbox/fantasy/checkbox.css
postcss-custom-properties: /home/static/projects/ufr-cash-order-ui/checkbox/fantasy/checkbox.css:105:8: variable '--font-weight' is undefined and used without a fallback
```

https://github.com/alfa-laboratory/arui-feather/blob/master/src/checkbox/fantasy/checkbox.css#L105
```sass
&.checkbox_checked .button__text {
    font-weight: var(--font-weight);
}
```

Result CSS:
```css
.checkbox_type_button.checkbox_checked .button__text {
    font-weight: var(--font-weight);
}
```
