### ISSUE TITLE
Непропорциональная кнопка Radio (m)

### ISSUE THREAD

**Issue by callmedmitriy** [alfa-laboratory/arui-feather#1163]
![Снимок экрана 2020-05-27 в 13 18 57](https://user-images.githubusercontent.com/19652590/83007735-c3a32980-a01c-11ea-84ed-5fafb8021a70.png)

В компоненте Radio (size='m') белая точка внутри при checked непропорциональна.
```CSS
.radio_size_m.radio_checked .radio__box::before {
    width: 5px; /* (Должна быть 4 или 6px) */
    height: 5px; /* (Должна быть 4 или 6px) */
}
```
